---
framework: mocha     
preRun:
  command:
    - npm install          
postMerge:
  pattern: 
    - "./test/*.js"
    - "./test/*/*.js"
preMerge:
  pattern:
    - "./test/*.js"
    - "./test/*/*.js"
postRun:
  command:
    - node --version
version: 1.0
