---
framework: mocha  
blocklist:
  - "./test/utils.js##utils.etag(body, encoding)"
preRun:
  command:
    - npm install          
postMerge:
  pattern: 
    - "./test/*.js"
    - "./test/*/*.js"
preMerge:
  pattern:
    - "./test/*.js"
    - "./test/*/*.js"
postRun:
  command:
    - node --version
version: 1.0.0
